version: "3.7"

services:
  api:
    build: Core/
    environment:
      ConnectionStrings__CyclingBuddiesContext: Server=postgres;Port=5432;Database=cycling_buddies;User ID=postgres;Password=postgres
    ports:
      - "5100:80"