version: "3.7"

volumes:
  postgres_data: {}
services:
  postgres:
    image: kartoza/postgis:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cycling_buddies
    ports:
      - "5432:5432"

  flyway:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/cycling_buddies
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on: ["postgres"]