version: "3.7"

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cycling_buddies
    ports:
      - "5432:5432"

  oidc:
    image: soluto/oidc-server-mock
    ports:
      - "44363:443"
    environment:
      ASPNETCORE_URLS: https://+:443;http://+80
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aireframe-oidc-mock.pfx
      USERS_CONFIGURATION_PATH: /tmp/config/users.json
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients.json
      API_SCOPES_PATH: /tmp/config/api-scopes.json
      API_RESOURCES_PATH: /tmp/config/api-resources.json
      SERVER_OPTIONS_INLINE: |
        {
          "IssuerUri": "https://localhost:44363",
        }
    volumes:
      - ./mocks/oidc:/tmp/config:ro
      - ~/.aspnet/https:/https:ro

  im-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: im
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      LC_COLLATE: 'C'
      LC_CTYPE: 'C'

  im-server:
    image: matrixdotorg/synapse:v1.52.0
    environment:
      - SYNAPSE_SERVER_NAME=localhost
      - SYNAPSE_REPORT_STATS=yes
    volumes:
      - ./matrix:/data
    ports:
      - 8008:8008
    depends_on:
      - im-db
