apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-db-migrate-job
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: "{{ .Chart.Name }}-db-migrate"
          image: "{{ .Values.image.registry }}/cycling-buddies-db-migration:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - info
            - repair
            - migrate
            - info
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db
                  key: port
            - name: FLYWAY_URL
              value: jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
      