{{- if .Values.serviceAccount.roleBinding -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.roleBinding }}
  namespace: default
subjects:
- kind: User
  name: {{ include "chart.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.roleBinding }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}