apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      {{ if eq .Values.service.type "NodePort" -}} nodePort: {{ .Values.service.nodePort }} {{ end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
