version: "3.7"

volumes:
  postgres_data: {}
services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cycling_buddies
    ports:
      - "5432:5432"