name: Backend - Production
on:
  push:
    branches:
      - master
jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      PROJECT_ID: ${{ secrets.TF_VAR_PROJECT_ID }}
      REPO_NAME: cycling-buddies-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.IMAGE_DEPLOY_GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
          export_default_credentials: true

      - name: Set release version
        run: echo "RELEASE_VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Build Image
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: docker build -t eu.gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG .

      - name: GCloud Auth
        run: gcloud auth configure-docker -q

      - name: Push Image
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: docker push eu.gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG

  build-db-migration:
    name: Build DB Migration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flyway
    env:
      PROJECT_ID: ${{ secrets.TF_VAR_PROJECT_ID }}
      REPO_NAME: cycling-buddies-db-migration
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.IMAGE_DEPLOY_GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
          export_default_credentials: true

      - name: Set release version
        run: echo "RELEASE_VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Build Image
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: docker build -t eu.gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG .

      - name: GCloud Auth
        run: gcloud auth configure-docker -q

      - name: Push Image
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: docker push eu.gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG

  helm-deploy:
    name: Helm Deploy
    needs: [build-backend, build-db-migration]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.HELM_DEPLOY_GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
          export_default_credentials: true

      - name: Set release version
        run: echo "RELEASE_VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: GCloud Auth
        run: gcloud auth configure-docker -q

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy
        env:
          GKE_ZONE: us-central1
          GKE_CLUSTER: ${{ secrets.CLUSTER_NAME }}
          DEPLOYMENT_NAME: cycling-buddies
          PROJECT_ID: ${{ secrets.TF_VAR_PROJECT_ID }}
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --zone $GKE_ZONE \
            --project $PROJECT_ID
          helm upgrade --install chart ./chart \
            --set image.tag=$IMAGE_TAG \
            --wait
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
