name: Deploy - Production

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Core
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPO_NAME: cycling-buddies-web
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.IMAGE_DEPLOY_GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Image
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: docker build -t eu.gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG .

      - name: GCloud Auth
        run: gcloud auth configure-docker -q

      - name: Push Image
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: docker push eu.gcr.io/$PROJECT_ID/$REPO_NAME:$IMAGE_TAG

  helm-deploy:
    name: Helm Deploy
    needs: [build-backend, build-db-migration]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.HELM_DEPLOY_GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: GCloud Auth
        run: gcloud auth configure-docker -q

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy
        env:
          GKE_ZONE: us-central1-a
          GKE_CLUSTER: ${{ secrets.CLUSTER_NAME }}
          DEPLOYMENT_NAME: cycling-buddies
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --zone $GKE_ZONE \
            --project $PROJECT_ID
          helm upgrade --install chart ./chart \
            --set image.tag=$IMAGE_TAG \
            --wait
          kubectl get services -o wide
