name: Website - Production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    env:
      REACT_APP_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      REACT_APP_AUTH0_API_AUDIENCE: ${{ secrets.AUTH0_API_AUDIENCE }}
      REACT_APP_API_HOST: ${{ secrets.API_HOST }}
      REACT_APP_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      REACT_APP_RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build React App
        run: npm run build
      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.FRONTEND_DEPLOY_GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
      - name: Deploy
        env:
          GCP_FRONTEND_BUCKET: ${{ secrets.GCP_FRONTEND_BUCKET }}
        run: gsutil -m rsync -R build gs://$GCP_FRONTEND_BUCKET
